### Đăng ký tài khoản mới
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "firstName": "Nguyễn Minh",
  "lastName": "Nhật",
  "phone": "04275189634",
  "password": "123456"
}

### Đăng nhập để lấy token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "phone": "0123456789",
  "password": "123456"
}

### Lấy danh sách user
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RhMzc3NTIyNjUwNjAyODU3MjhhY2QiLCJwaG9uZSI6IjAxMjM0NTY3ODkiLCJpYXQiOjE3NDI2NDk2NTMsImV4cCI6MTc0MjczNjA1M30.0snTwl6fCeBe9KdgB4BtXD4mrrcvE1_4ADW8MmqA5xE

### Lấy user hiện tại
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RhMzc3NTIyNjUwNjAyODU3MjhhY2QiLCJwaG9uZSI6IjAxMjM0NTY3ODkiLCJpYXQiOjE3NDI2NDk2NTMsImV4cCI6MTc0MjczNjA1M30.0snTwl6fCeBe9KdgB4BtXD4mrrcvE1_4ADW8MmqA5xE

### Lấy user theo phone
GET http://localhost:3000/users/0123456789
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RhMzc3NTIyNjUwNjAyODU3MjhhY2QiLCJwaG9uZSI6IjAxMjM0NTY3ODkiLCJpYXQiOjE3NDI2NDk2NTMsImV4cCI6MTc0MjczNjA1M30.0snTwl6fCeBe9KdgB4BtXD4mrrcvE1_4ADW8MmqA5xE

### Lấy user theo id
GET http://localhost:3000/users/67d8e94f75c45e1b6538929b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RhMzc3NTIyNjUwNjAyODU3MjhhY2QiLCJwaG9uZSI6IjAxMjM0NTY3ODkiLCJpYXQiOjE3NDI2NDk2NTMsImV4cCI6MTc0MjczNjA1M30.0snTwl6fCeBe9KdgB4BtXD4mrrcvE1_4ADW8MmqA5xE